DROP TABLE IF EXISTS items;

CREATE TABLE items (id SMALLSERIAL UNIQUE, value SMALLINT NOT NULL , version SMALLSERIAL NOT NULL);

INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);
INSERT INTO items (value, version)VALUES (0, 0);