drop table if exists products;

set search_path to boot;

create table if not exists products (id SERIAL, title VARCHAR(50), price INT);

insert into products (title, price) values ('Currants', 13);
insert into products (title, price) values ('Mushroom - Portebello', 50);
insert into products (title, price) values ('Clams - Canned', 81);
insert into products (title, price) values ('Appetizer - Assorted Box', 85);
insert into products (title, price) values ('Rum - Spiced, Captain Morgan', 8);
insert into products (title, price) values ('Wine - White, Pelee Island', 23);
insert into products (title, price) values ('Wine - Lamancha Do Crianza', 83);
insert into products (title, price) values ('Galliano', 14);
insert into products (title, price) values ('Fish - Base, Bouillion', 60);
insert into products (title, price) values ('Wine - Jafflin Bourgongone', 75);
insert into products (title, price) values ('Plastic Wrap', 16);
insert into products (title, price) values ('Rosemary - Dry', 29);
insert into products (title, price) values ('Wine - Cava Aria Estate Brut', 15);
insert into products (title, price) values ('Creme De Banane - Marie', 80);
insert into products (title, price) values ('Ham - Proscuitto', 89);
insert into products (title, price) values ('Marjoram - Dried, Rubbed', 75);
insert into products (title, price) values ('Tarragon - Fresh', 25);
insert into products (title, price) values ('Quail - Eggs, Fresh', 75);
insert into products (title, price) values ('Wine - Chablis 2003 Champs', 99);
insert into products (title, price) values ('Corn Syrup', 68);
insert into products (title, price) values ('Cookies Almond Hazelnut', 77);
insert into products (title, price) values ('Beef - Ground Medium', 65);
insert into products (title, price) values ('Ecolab Digiclean Mild Fm', 50);
insert into products (title, price) values ('Wonton Wrappers', 34);
insert into products (title, price) values ('Stainless Steel Cleaner Vision', 92);
insert into products (title, price) values ('Chocolate - Milk', 100);
insert into products (title, price) values ('Soup - Boston Clam Chowder', 88);
insert into products (title, price) values ('Chilli Paste, Hot Sambal Oelek', 67);
insert into products (title, price) values ('Tomato - Tricolor Cherry', 92);
insert into products (title, price) values ('Wine - Redchard Merritt', 47);
insert into products (title, price) values ('Sorrel - Fresh', 19);
insert into products (title, price) values ('Milk - 2%', 28);
insert into products (title, price) values ('Bay Leaf Ground', 14);
insert into products (title, price) values ('Curry Powder Madras', 59);
insert into products (title, price) values ('Milk - Chocolate 250 Ml', 19);
insert into products (title, price) values ('Pepper - Orange', 57);
insert into products (title, price) values ('Mushroom Morel Fresh', 64);
insert into products (title, price) values ('Broom - Angled', 70);
insert into products (title, price) values ('Lettuce - Frisee', 62);
insert into products (title, price) values ('Shrimp - Black Tiger 13/15', 43);
insert into products (title, price) values ('Mix - Cappucino Cocktail', 91);
insert into products (title, price) values ('Pasta - Penne, Rigate, Dry', 27);
insert into products (title, price) values ('Cheese - Gouda', 67);
insert into products (title, price) values ('Veal - Inside, Choice', 33);
insert into products (title, price) values ('Peas Snow', 44);
insert into products (title, price) values ('Beans - Wax', 15);
insert into products (title, price) values ('Hot Choc Vending', 38);
insert into products (title, price) values ('Beer - Blue Light', 40);
insert into products (title, price) values ('Sugar - Icing', 55);
insert into products (title, price) values ('Cream - 18%', 44);
insert into products (title, price) values ('Cookies - Englishbay Chochip', 70);
insert into products (title, price) values ('Soy Protein', 80);
insert into products (title, price) values ('Sponge Cake Mix - Chocolate', 14);
insert into products (title, price) values ('Cheese - Cheddar, Medium', 12);
insert into products (title, price) values ('Vinegar - Champagne', 4);
insert into products (title, price) values ('Wine - Cousino Macul Antiguas', 82);
insert into products (title, price) values ('Tomatoes - Orange', 26);
insert into products (title, price) values ('Ecolab - Hand Soap Form Antibac', 48);
insert into products (title, price) values ('Curry Paste - Madras', 32);
insert into products (title, price) values ('Soup - Campbells Chili Veg', 100);
insert into products (title, price) values ('Jolt Cola - Electric Blue', 23);
insert into products (title, price) values ('Wine - Magnotta - Bel Paese White', 16);
insert into products (title, price) values ('Mushroom - Morel Frozen', 44);
insert into products (title, price) values ('Lamb Tenderloin Nz Fr', 12);
insert into products (title, price) values ('Beef - Ox Tail, Frozen', 24);
insert into products (title, price) values ('Asparagus - White, Canned', 42);
insert into products (title, price) values ('Sorrel - Fresh', 41);
insert into products (title, price) values ('Longos - Lasagna Beef', 39);
insert into products (title, price) values ('Chips Potato Reg 43g', 96);
insert into products (title, price) values ('Beef - Montreal Smoked Brisket', 38);
insert into products (title, price) values ('Soup Campbells Turkey Veg.', 15);
insert into products (title, price) values ('Kippers - Smoked', 81);
insert into products (title, price) values ('Puree - Strawberry', 42);
insert into products (title, price) values ('Dc Hikiage Hira Huba', 4);
insert into products (title, price) values ('Turkey - Breast, Double', 5);
insert into products (title, price) values ('Mace', 58);
insert into products (title, price) values ('Sugar - Invert', 7);
insert into products (title, price) values ('Mushroom - White Button', 65);
insert into products (title, price) values ('Puree - Raspberry', 4);
insert into products (title, price) values ('Eggplant - Regular', 30);
insert into products (title, price) values ('Pork - Tenderloin, Frozen', 24);
insert into products (title, price) values ('Wine - Red, Cooking', 50);
insert into products (title, price) values ('Pepper - Black, Ground', 60);
insert into products (title, price) values ('Bagel - Everything', 98);
insert into products (title, price) values ('Hersey Shakes', 7);
insert into products (title, price) values ('Sauce - Caesar Dressing', 79);
insert into products (title, price) values ('Savory', 52);
insert into products (title, price) values ('Smirnoff Green Apple Twist', 25);
insert into products (title, price) values ('Squid - Breaded', 92);
insert into products (title, price) values ('Lobster - Baby, Boiled', 57);
insert into products (title, price) values ('Asparagus - White, Fresh', 94);
insert into products (title, price) values ('Fudge - Chocolate Fudge', 7);
insert into products (title, price) values ('Mix - Cocktail Strawberry Daiquiri', 100);
insert into products (title, price) values ('Cheese - Victor Et Berthold', 46);
insert into products (title, price) values ('Dasheen', 75);
insert into products (title, price) values ('Ham - Cooked', 91);
insert into products (title, price) values ('Sultanas', 50);
insert into products (title, price) values ('Tomato Paste', 59);
insert into products (title, price) values ('Vinegar - White Wine', 6);
insert into products (title, price) values ('Pepper - Black, Crushed', 78);